# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ace44ccdd1d1d335f8f2d4e66987ad7f0d69732b7683f1064de2f90ff01a8ff3e8cfea374e44be89c36b6605e874182b04abebfe99a24dbd79b1282e8af7d9b

test:
  secret_key_base: bef5ed68a4f5c7822b8531098fe805f23c254c9d44507a5d865e0d76bc682869e76b51e9b05a4025f8e1576a1cb61534fccefb81a68b4af0ef0f01603d91714c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
